#!/bin/sh

if [ $# -ne 1 ]
then
	echo "Need gpio number"
	exit 1
fi

if ! [ -d "/sys/class/gpio/gpio$1" ]
then
	echo $1 > /sys/class/gpio/export
	echo "GPIO $1 exported"
	echo out > /sys/class/gpio/gpio$1/direction
	echo "GPIO $1 direction is out"
fi

echo 0 > /sys/class/gpio/gpio$1/value

echo "GPIO $1 OFF"

exit 0
